### PR TITLE
fix: requeue request when optimistic lock error found

### LINKED ISSUE #493: So many error message "cannot update status: Operation cannot be fulfilled on xxx.harbors.goharbor.io"
So many error message "cannot update status: Operation cannot be fulfilled on xxx.harbors.goharbor.io" will be found in the log after `kubectl apply -f manifests/samples/full_stack_other_fs.yaml`

```
2021-03-14T09:34:25.820Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "goharbor.io", "reconcilerKind": "HarborCluster", "controller": "harborcluster", "name": "harborcluster-sample", "namespace": "cluster-sample-ns", "error": "cannot set status to error: cannot set conditions to error: cannot prepare owner status: cannot update status: Operation cannot be fulfilled on harborclusters.goharbor.io \"harborcluster-sample\": the object has been modified; please apply your changes to the latest version and try again: cannot prepare owner status: cannot update status: Operation cannot be fulfilled on harborclusters.goharbor.io \"harborcluster-sample\": the object has been modified; please apply your changes to the latest version and try again", "errorVerbose": "Operation cannot be fulfilled on harborclusters.goharbor.io \"harborcluster-sample\": the object has been modified; please apply your changes to the latest version and try again\ncannot update status\ngithub.com/goharbor/harbor-operator/pkg/controller.(*Controller).PrepareStatus\n\t/home/ubuntu/Repos/harbor-operator/pkg/controller/status.go:35\ngithub.com/goharbor/harbor-operator/controllers/goharbor/harborcluster.(*Reconciler).Reconcile\n\t/home/ubuntu/Repos/harbor-operator/controllers/goharbor/harborcluster/harborcluster.go:47\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/ubuntu/go/1.15.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/ubuntu/go/1.15.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/ubuntu/go/1.15.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90\nruntime.goexit\n\t/home/ubuntu/.goenv/versions/1.15.6/src/runtime/asm_amd64.s:1374\ncannot prepare owner status\ngithub.com/goharbor/harbor-operator/controllers/goharbor/harborcluster.(*Reconciler).Reconcile\n\t/home/ubuntu/Repos/harbor-operator/controllers/goharbor/harborcluster/harborcluster.go:48\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/ubuntu/go/1.15.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/ubuntu/go/1.15.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/ubuntu/go/1.15.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90\nruntime.goexit\n\t/home/ubuntu/.goenv/versions/1.15.6/src/runtime/asm_amd64.s:1374\ncannot set status to error: cannot set conditions to error: cannot prepare owner status: cannot update status: Operation cannot be fulfilled on harborclusters.goharbor.io \"harborcluster-sample\": the object has been modified; please apply your changes to the latest version and try again\ngithub.com/goharbor/harbor-operator/pkg/controller.(*Controller).HandleError\n\t/home/ubuntu/Repos/harbor-operator/pkg/controller/errors.go:50\ngithub.com/goharbor/harbor-operator/controllers/goharbor/harborcluster.(*Reconciler).Reconcile\n\t/home/ubuntu/Repos/harbor-operator/controllers/goharbor/harborcluster/harborcluster.go:48\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/ubuntu/go/1.15.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/ubuntu/go/1.15.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/ubuntu/go/1.15.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90\nruntime.goexit\n\t/home/ubuntu/.goenv/versions/1.15.6/src/runtime/asm_amd64.s:1374"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/ubuntu/go/1.15.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/home/ubuntu/go/1.15.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90
```

```
2021-03-14T09:34:36.398Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "goharbor.io", "reconcilerKind": "Harbor", "controller": "harbor", "name": "harborcluster-sample-harbor", "namespace": "cluster-sample-ns", "error": "cannot set status to error: cannot set conditions to error: cannot prepare owner status: cannot update status: Operation cannot be fulfilled on harbors.goharbor.io \"harborcluster-sample-harbor\": the object has been modified; please apply your changes to the latest version and try again: cannot prepare owner status: cannot update status: Operation cannot be fulfilled on harbors.goharbor.io \"harborcluster-sample-harbor\": the object has been modified; please apply your changes to the latest version and try again", "errorVerbose": "Operation cannot be fulfilled on harbors.goharbor.io \"harborcluster-sample-harbor\": the object has been modified; please apply your changes to the latest version and try again\ncannot update status\ngithub.com/goharbor/harbor-operator/pkg/controller.(*Controller).PrepareStatus\n\t/home/ubuntu/Repos/harbor-operator/pkg/controller/status.go:35\ngithub.com/goharbor/harbor-operator/pkg/controller.(*Controller).Run\n\t/home/ubuntu/Repos/harbor-operator/pkg/controller/common.go:170\ngithub.com/goharbor/harbor-operator/pkg/controller.(*Controller).Reconcile\n\t/home/ubuntu/Repos/harbor-operator/pkg/controller/common.go:134\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/ubuntu/go/1.15.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/ubuntu/go/1.15.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/ubuntu/go/1.15.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90\nruntime.goexit\n\t/home/ubuntu/.goenv/versions/1.15.6/src/runtime/asm_amd64.s:1374\ncannot prepare owner status\ngithub.com/goharbor/harbor-operator/pkg/controller.(*Controller).Run\n\t/home/ubuntu/Repos/harbor-operator/pkg/controller/common.go:171\ngithub.com/goharbor/harbor-operator/pkg/controller.(*Controller).Reconcile\n\t/home/ubuntu/Repos/harbor-operator/pkg/controller/common.go:134\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/ubuntu/go/1.15.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/ubuntu/go/1.15.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/ubuntu/go/1.15.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90\nruntime.goexit\n\t/home/ubuntu/.goenv/versions/1.15.6/src/runtime/asm_amd64.s:1374\ncannot set status to error: cannot set conditions to error: cannot prepare owner status: cannot update status: Operation cannot be fulfilled on harbors.goharbor.io \"harborcluster-sample-harbor\": the object has been modified; please apply your changes to the latest version and try again\ngithub.com/goharbor/harbor-operator/pkg/controller.(*Controller).HandleError\n\t/home/ubuntu/Repos/harbor-operator/pkg/controller/errors.go:50\ngithub.com/goharbor/harbor-operator/pkg/controller.(*Controller).Reconcile\n\t/home/ubuntu/Repos/harbor-operator/pkg/controller/common.go:135\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/ubuntu/go/1.15.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/ubuntu/go/1.15.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/ubuntu/go/1.15.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90\nruntime.goexit\n\t/home/ubuntu/.goenv/versions/1.15.6/src/runtime/asm_amd64.s:1374"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/ubuntu/go/1.15.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/home/ubuntu/go/1.15.6/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/home/ubuntu/go/1.15.6/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90
```

### PR DESCRIPTION
**Pull request by heww**
Do manual retry without error when an optimistic lock error found. For
more info, see https://github.com/kubernetes/kubernetes/issues/28149

Closes #493

Signed-off-by: He Weiwei <hweiwei@vmware.com>

### CODE REVIEW

File: pkg/controller/errors.go [hunk 1]
```diff
@@ -12,15 +14,27 @@ import (
 	"sigs.k8s.io/controller-runtime/pkg/client"
 )
 
+const optimisticLockErrorMsg = "the object has been modified; please apply your changes to the latest version and try again"
+
 type causer interface {
 	Cause() error
 }
 
+func IsOptimisticLockError(err error) bool {
```
Comment (steven-zou) [inline pkg/controller/errors.go:23]: Can this error be checked by errors.IsConflict(error) in the api/errors package?

**Review by steven-zou — COMMENTED** [review]
check my comments, @heww

**Review by steven-zou — APPROVED** [review]
LGTM

**Review by bitsf — APPROVED** [review]
