### PR TITLE
fix(bug) notary/trivy can't install with github token

### LINKED ISSUE #118: It seems Harbor CR does not update
Reproduce steps:

install harbor core components with `make sample`, harbor "sample" is deployed 

install full harbor with `make sample-harbor-full`, no more components are deployed.

expectations: the optional components like `notary`, `chartmuseum` and `trivy` should be deployed.

### PR DESCRIPTION
**Pull request by bitsf**
close #118
add github token injection for trivy component
remote github token for notary, and use internal logic to do migration

### CODE REVIEW

File: controllers/goharbor/chartmuseum/chartmuseum.go [hunk 1]
```diff
@@ -23,7 +23,7 @@ const (
 	DefaultConfigTemplatePath = "/etc/harbor-operator/chartmuseum-config.yaml.tmpl"
 	ConfigTemplateKey         = "template-content"
 	ConfigImageKey            = "docker-image"
-	DefaultImage              = "goharbor/chartmuseum-photon:v2.0.0"
+	DefaultImage              = "ap.cicd.harbor.vmwarecna.net/proxy/goharbor/chartmuseum-photon:v2.0.0"
```
Comment (steven-zou) [inline controllers/goharbor/chartmuseum/chartmuseum.go:26]: Is the registry publish for all the internet?

File: controllers/goharbor/harbor/notarysigner.go [hunk 2]
```diff
@@ -328,6 +329,17 @@ func (r *Reconciler) GetDefaultNotarySignerMigrationSource(ctx context.Context,
 type NotarySignerMigrationSecret graph.Resource
 
 func (r *Reconciler) AddNotarySignerMigrationSecret(ctx context.Context, harbor *goharborv1alpha2.Harbor) (NotarySignerMigrationSecret, error) {
+	logger.Get(ctx).WithName("notaryserver").Info("AddNotarySignerMigrationSecret", "MigrationEnabled", *harbor.Spec.Notary.MigrationEnabled)
+
+	if !*harbor.Spec.Notary.MigrationEnabled {
+		return nil, nil
+	}
+
+	// do not use github now
```
Comment (steven-zou) [inline controllers/goharbor/harbor/notarysigner.go:338]: Do we need this hardcoded code gate for disabling GitHub token reading?

File: controllers/goharbor/harbor/notaryserver.go [hunk 3]
```diff
@@ -165,6 +167,17 @@ func (r *Reconciler) GetDefaultNotaryServerMigrationSource(ctx context.Context,
 type NotaryServerMigrationSecret graph.Resource
 
 func (r *Reconciler) AddNotaryServerMigrationSecret(ctx context.Context, harbor *goharborv1alpha2.Harbor) (NotaryServerMigrationSecret, error) {
+	logger.Get(ctx).WithName("notaryserver").Info("AddNotaryServerMigrationSecret", "MigrationEnabled", *harbor.Spec.Notary.MigrationEnabled)
+
+	if !*harbor.Spec.Notary.MigrationEnabled {
+		return nil, nil
+	}
+
+	// do not use github now
```
Comment (steven-zou) [inline controllers/goharbor/harbor/notaryserver.go:176]: Do we need this hardcoded code gate for disabling GitHub token reading?

**Review by steven-zou — COMMENTED** [review]
Let's have more discussions about this PR?

File: controllers/goharbor/harbor/trivy.go [hunk 4]
```diff
@@ -75,7 +76,11 @@ func (r *Reconciler) GetTrivyUpdateSecret(ctx context.Context, harbor *goharborv
 
 	token, err := r.GetGithubToken(TrivyGithubCredentialsConfigKey)
 	if err != nil {
-		return nil, serrors.UnrecoverrableError(err, serrors.OperatorReason, "cannot get default github credentials")
+		if _, ok := err.(configstore.ErrItemNotFound); ok {
```
Comment (steven-zou) [inline controllers/goharbor/harbor/trivy.go:79]: Why return nil, nil when it is not found?

File: controllers/goharbor/notaryserver/deployments.go [hunk 5]
```diff
@@ -107,24 +103,41 @@ func (r *Reconciler) GetDeployment(ctx context.Context, notary *goharborv1alpha2
 	}
 
 	initContainers := []corev1.Container{}
+	migrateCmd := ""
+	migrationEnvs := []corev1.EnvVar{}
+
+	if notary.Spec.MigrationEnabled == nil || *notary.Spec.MigrationEnabled {
```
Comment (steven-zou) [inline controllers/goharbor/notaryserver/deployments.go:109]: default is true?

Comment (steven-zou) [reply controllers/goharbor/notaryserver/deployments.go:109]: not set means migration is enabled?

**Review by steven-zou — COMMENTED** [review]
commented

File: controllers/goharbor/harbor/trivy.go (hunk 4 above)
Comment (bitsf) [reply controllers/goharbor/harbor/trivy.go:79]: for trivy, it doesn't have to have a github token

File: controllers/goharbor/notaryserver/deployments.go (hunk 5 above)
Comment (bitsf) [reply controllers/goharbor/notaryserver/deployments.go:109]: yes, the default is true, or fresh installation will be fail

File: controllers/goharbor/harbor/trivy.go (hunk 4 above)
Comment (steven-zou) [reply controllers/goharbor/harbor/trivy.go:79]: I don't think we should check it here. For the case of not setting, we should check the token secret ref in the CR spec.

Comment (bitsf) [reply controllers/goharbor/harbor/trivy.go:79]: it will find another default token if not set inspec, and if neither is found, it will return ErrItemNotFound

Comment (steven-zou) [reply controllers/goharbor/harbor/trivy.go:79]: Offline discussion with zm, let's keep the way used in the code

**Review by steven-zou — APPROVED** [review]
LGTM
