### PR TITLE
fix(trivy) failed pull image

### LINKED ISSUE #246: trivy is not function well
install harbor with trivy enabled, and also setup the correct github token
but scan failed
image

### PR DESCRIPTION
**Pull request by bitsf**
close #246
trivy can't pull image with auth fail because it is not using internal auth url, because core_url doesn't have port

### CODE REVIEW

**Comment by bitsf** [comment]
this issue is because harbor pr https://github.com/goharbor/harbor/pull/11755/files not handle trivy request well

File: controllers/goharbor/core/deployments.go [hunk 1]
```diff
@@ -119,9 +119,16 @@ func (r *Reconciler) GetDeployment(ctx context.Context, core *goharborv1alpha2.C
 		scheme = "https"
 	}
 
+	host := r.NormalizeName(ctx, core.GetName())
+	if core.Spec.Components.TLS.Enabled() {
+		host += ":443"
+	} else {
+		host += ":80"
```
Comment (steven-zou) [inline controllers/goharbor/core/deployments.go:126]: why do we need to set such default ports?

the protocol scheme can not resolve the problem?

**Review by steven-zou — COMMENTED** [review]
I have questions about the change

File: controllers/goharbor/core/deployments.go (hunk 1 above)
Comment (bitsf) [reply controllers/goharbor/core/deployments.go:126]: because weiwei concat the port forcely with this PR
https://github.com/aquasecurity/harbor-scanner-trivy/issues/108
image

**Review by steven-zou — APPROVED** [review]
LGTM
