### PR TITLE
Make PostgreSQL secrets name template configurable

### LINKED ISSUE #572: Wrong secret name referenced when using inClusterDatabase
**Expected behavior and actual behavior:**
I'm trying to create a harbor cluster with `inClusterDatabase` enabled. After creating the PostgreSQL database using the Zalando PostgresSQL Operator, the harbor-operator seems to try to lookup a secret named `harbor.postgresql-harbor-harborcluster-sample.credentials` where the actual secret created by the zalando operator has a suffix `.postgresql.acid.zalan.do` and is thus named `harbor.postgresql-harbor-harborcluster-sample.credentials.postgresql.acid.zalan.do`.

Relevant log entry:
```
2021-04-19T16:10:15.522Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "goharbor.io", "reconcilerKind": "HarborCluster", "controller": "harborcluster", "name": "harborcluster-sample", "namespace": "harbor", "error": "reconcile dependent services error: gos.Group error: Secret \"harbor.postgresql-harbor-harborcluster-sample.credentials\" not found"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90
```

**Steps to reproduce the problem:**
1. Install redis-operator, postgresql-operator, certmanager
2. Install harbor-operator
3. Install sample from `https://github.com/goharbor/harbor-operator/blob/master/manifests/samples/harbor_core_fs.yaml`

**Versions:**
- harbor operator version: dev_master (docker image)
- harbor version: 2.2.1
- kubernetes version: 1.20.2
- postgres-operator: 1.6.2

### PR DESCRIPTION
**Pull request by dajudge**
Fixes #572

Signed-off-by: Alex Stockinger <mail@alexstockinger.de>

### CODE REVIEW

File: pkg/cluster/controllers/database/readiness.go [hunk 1]
```diff
@@ -161,8 +165,34 @@ func (p *PostgreSQLController) GetInClusterDatabaseConn(ctx context.Context, har
...
+
+func (f *SecretsTemplate) Format(a ...string) string {
+	res := string(*f)
+
+	for i := 0; i < len(a); i += 2 {
+		res = strings.Replace(res, "{"+a[i]+"}", a[i+1], -1)
+	}
+
+	return res
+}
```
Comment (dajudge) [inline pkg/cluster/controllers/database/readiness.go:178]: @steven-zou this is a blunt copy from https://github.com/zalando/postgres-operator/blob/0745ce7cce63ab6431103d27eb08e54ec47d2b15/pkg/util/config/util.go#L232

does this need to be re-written to avoid licensing issues?

Comment (dajudge) [reply pkg/cluster/controllers/database/readiness.go]: @Ghostbaby maybe you could say sth about this?

**Comment by dajudge** [comment]
@steven-zou @Ghostbaby @bitsf plz have a look at the comment above regarding the piece of code from the postgres-operator project before merging the PR

https://github.com/goharbor/harbor-operator/pull/575#pullrequestreview-640660580

**Review by bitsf — APPROVED** [review]

**Review by Ghostbaby — APPROVED** [review]
lgtm
