### PR TITLE
fix(harbor class) Close #399

### LINKED ISSUE #399: Issue found in the Harbor class

### PR DESCRIPTION
**Pull request by sguyennet**
Signed-off-by: Simon Guyennet <simon.guyennet@corp.ovh.com>

### CODE REVIEW

File: pkg/controller/mutation.go [hunk 1]
```diff
@@ -30,6 +31,15 @@ const (
 func (c *Controller) GlobalMutateFn(ctx context.Context) (resources.Mutable, error) {
 	var mutate resources.Mutable = mutation.NoOp
 
+	className, err := c.GetClassName(ctx)
+	if err != nil {
+		return nil, errors.Wrap(err, "cannot get class name")
+	}
+
+	if className != "" {
+		mutate.AppendMutation(mutation.GetAnnotationsMutation(HarborClassAnnotation, className))
```
Comment (holyhope) [inline pkg/controller/mutation.go:40]:
```suggestion
		mutate.AppendMutation(mutation.GetAnnotationsMutation(goharborv1alpha2.HarborClassAnnotation, className))
```

File: pkg/controller/mutation.go [hunk 2]
```diff
@@ -18,8 +18,9 @@ import (
 var ErrorOwnerNotFound = errors.New("owner not found")
 
 const (
-	WarningAnnotation = "goharbor.io/warning"
-	WarningValueTmpl  = "⚠️ This Resource is managed by *%s* ⚠️"
+	HarborClassAnnotation = "goharbor.io/harbor-class"
```
Comment (holyhope) [inline pkg/controller/mutation.go:21]:
```suggestion
```

**Review by holyhope — CHANGES_REQUESTED** [review]

File: pkg/controller/mutation.go [hunk 3]
```diff
@@ -18,8 +18,8 @@ import (
 var ErrorOwnerNotFound = errors.New("owner not found")
 
 const (
-	WarningAnnotation = "goharbor.io/warning"
-	WarningValueTmpl  = "⚠️ This Resource is managed by *%s* ⚠️"
+	WarningAnnotation     = "goharbor.io/warning"
+	WarningValueTmpl      = "⚠️ This Resource is managed by *%s* ⚠️"
```
Comment (holyhope) [inline pkg/controller/mutation.go:22]:
```suggestion
	WarningAnnotation = "goharbor.io/warning"
	WarningValueTmpl  = "⚠️ This Resource is managed by *%s* ⚠️"
```

**Review by holyhope — APPROVED** [review]

**Review by holyhope — APPROVED** [review]

**Review by steven-zou — APPROVED** [review]
LGTM
